### ISSUE TITLE
Wrong version in Cargo

### ISSUE THREAD

**Issue by e-oz** [vlad003/rust-oath#1]
Can't add it to cargo with just "oath = 0.1.3" - some old code with "feature" on the first line.
Have to write

```
oath = { git = "https://github.com/vlad003/rust-oath.git", rev = "f3f6b37" }
```

to get new code (and then it successfully compiles).
Maybe you need to update version in Cargo.

**Comment by avacariu** [comment]
I published a new version (0.1.4), does that help?

The stuff that's on crates.io (even for 0.1.3) is exactly what's in this repo.
