### ISSUE TITLE
totp doesn't work

### ISSUE THREAD

**Issue by e-oz** [vlad003/rust-oath#2]
totp doesn't work with google authenticator, always wrong code, I tried a lot of different arguments.
This library works fine on the same machine and without any settings:
https://github.com/breard-r/r2fa

**Comment by avacariu** [comment]
Can you give me an example input that doesn't work (and the expected output)?

**Comment by e-oz** [comment]
Please try "AAAAAAAAAAAAAAAA" as key:
https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/test?secret=AAAAAAAAAAAAAAAA

**Comment by avacariu** [comment]
Sorry for the late reply. 

I just looked into it, and Google Authenticator keys are in base 32. You have to convert them before they can be used.

I don't work much with Rust these days so I don't know a good way of converting from base 32 (there's probably a crate that does it), but as an example, Your key `AAAAAAAAAAAAAAAA` is converted to hex as `00000000000000000000`, which can be used with the `from_hex` function.

**Comment by avacariu** [comment]
I've added a short explanation on how to convert from bas32 in the README.
